[package]
name = "o2versioner"
version = "0.1.0"
authors = ["Lichen Liu <issac.liu@mail.utoronto.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
actix-web = "3"
env_logger = "0.8"
log = "0.4"